namespace Glacier.Tensor.Compute;

internal static class TensorCoreGemmKernel
{
    public const string PtxSource = @"//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-37862127
// Cuda compilation tools, release 13.3, V13.3.33
// Based on NVVM 7.0.1
//

.version 9.3
.target sm_89
.address_size 64

	// .globl	tensor_core_gemm_fp16
// _ZZ21tensor_core_gemm_fp32E3s_a has been demoted
// _ZZ21tensor_core_gemm_fp32E3s_b has been demoted

.visible .entry tensor_core_gemm_fp16(
	.param .u64 tensor_core_gemm_fp16_param_0,
	.param .u64 tensor_core_gemm_fp16_param_1,
	.param .u64 tensor_core_gemm_fp16_param_2,
	.param .u32 tensor_core_gemm_fp16_param_3,
	.param .u32 tensor_core_gemm_fp16_param_4,
	.param .u32 tensor_core_gemm_fp16_param_5
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<146>;
	.reg .b32 	%r<120>;
	.reg .b64 	%rd<49>;


	ld.param.u64 	%rd10, [tensor_core_gemm_fp16_param_0];
	ld.param.u64 	%rd11, [tensor_core_gemm_fp16_param_1];
	ld.param.u64 	%rd9, [tensor_core_gemm_fp16_param_2];
	ld.param.u32 	%r19, [tensor_core_gemm_fp16_param_3];
	ld.param.u32 	%r17, [tensor_core_gemm_fp16_param_4];
	ld.param.u32 	%r18, [tensor_core_gemm_fp16_param_5];
	cvta.to.global.u64 	%rd1, %rd11;
	cvta.to.global.u64 	%rd2, %rd10;
	mov.u32 	%r20, %ctaid.x;
	shl.b32 	%r1, %r20, 4;
	setp.ge.s32 	%p1, %r1, %r19;
	mov.u32 	%r21, %ctaid.y;
	shl.b32 	%r2, %r21, 4;
	setp.ge.s32 	%p2, %r2, %r17;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_10;

	setp.gt.s32 	%p4, %r18, 0;
	@%p4 bra 	$L__BB0_3;
	bra.uni 	$L__BB0_2;

$L__BB0_3:
	mul.lo.s32 	%r23, %r1, %r18;
	cvt.s64.s32 	%rd3, %r23;
	cvt.s64.s32 	%rd4, %r2;
	add.s32 	%r24, %r18, -1;
	shr.u32 	%r25, %r24, 4;
	add.s32 	%r3, %r25, 1;
	and.b32  	%r119, %r3, 3;
	setp.lt.u32 	%p5, %r24, 48;
	mov.u32 	%r117, 0;
	mov.f32 	%f138, 0f00000000;
	mov.f32 	%f139, %f138;
	mov.f32 	%f140, %f138;
	mov.f32 	%f141, %f138;
	mov.f32 	%f142, %f138;
	mov.f32 	%f143, %f138;
	mov.f32 	%f144, %f138;
	mov.f32 	%f145, %f138;
	@%p5 bra 	$L__BB0_6;

	sub.s32 	%r116, %r3, %r119;
	shl.b32 	%r27, %r17, 4;
	mul.wide.s32 	%rd5, %r27, 2;
	mov.u32 	%r117, 0;
	mov.f32 	%f138, 0f00000000;

$L__BB0_5:
	cvt.s64.s32 	%rd12, %r117;
	add.s64 	%rd13, %rd12, %rd3;
	shl.b64 	%rd14, %rd13, 1;
	add.s64 	%rd15, %rd2, %rd14;
	wmma.load.a.sync.aligned.row.m16n16k16.global.f16 	{%r28, %r29, %r30, %r31, %r32, %r33, %r34, %r35}, [%rd15], %r18;
	mul.lo.s32 	%r36, %r117, %r17;
	cvt.s64.s32 	%rd16, %r36;
	add.s64 	%rd17, %rd16, %rd4;
	shl.b64 	%rd18, %rd17, 1;
	add.s64 	%rd19, %rd1, %rd18;
	wmma.load.b.sync.aligned.row.m16n16k16.global.f16 	{%r37, %r38, %r39, %r40, %r41, %r42, %r43, %r44}, [%rd19], %r17;
	wmma.mma.sync.aligned.row.row.m16n16k16.f32.f32 {%f82, %f83, %f84, %f85, %f86, %f87, %f88, %f89}, {%r28, %r29, %r30, %r31, %r32, %r33, %r34, %r35}, {%r37, %r38, %r39, %r40, %r41, %r42, %r43, %r44}, {%f145, %f144, %f143, %f142, %f141, %f140, %f139, %f138};
	add.s32 	%r45, %r117, 16;
	cvt.s64.s32 	%rd20, %r45;
	add.s64 	%rd21, %rd20, %rd3;
	shl.b64 	%rd22, %rd21, 1;
	add.s64 	%rd23, %rd2, %rd22;
	wmma.load.a.sync.aligned.row.m16n16k16.global.f16 	{%r46, %r47, %r48, %r49, %r50, %r51, %r52, %r53}, [%rd23], %r18;
	add.s64 	%rd24, %rd19, %rd5;
	wmma.load.b.sync.aligned.row.m16n16k16.global.f16 	{%r54, %r55, %r56, %r57, %r58, %r59, %r60, %r61}, [%rd24], %r17;
	wmma.mma.sync.aligned.row.row.m16n16k16.f32.f32 {%f90, %f91, %f92, %f93, %f94, %f95, %f96, %f97}, {%r46, %r47, %r48, %r49, %r50, %r51, %r52, %r53}, {%r54, %r55, %r56, %r57, %r58, %r59, %r60, %r61}, {%f82, %f83, %f84, %f85, %f86, %f87, %f88, %f89};
	add.s32 	%r62, %r117, 32;
	cvt.s64.s32 	%rd25, %r62;
	add.s64 	%rd26, %rd25, %rd3;
	shl.b64 	%rd27, %rd26, 1;
	add.s64 	%rd28, %rd2, %rd27;
	wmma.load.a.sync.aligned.row.m16n16k16.global.f16 	{%r63, %r64, %r65, %r66, %r67, %r68, %r69, %r70}, [%rd28], %r18;
	add.s64 	%rd29, %rd24, %rd5;
	wmma.load.b.sync.aligned.row.m16n16k16.global.f16 	{%r71, %r72, %r73, %r74, %r75, %r76, %r77, %r78}, [%rd29], %r17;
	wmma.mma.sync.aligned.row.row.m16n16k16.f32.f32 {%f98, %f99, %f100, %f101, %f102, %f103, %f104, %f105}, {%r63, %r64, %r65, %r66, %r67, %r68, %r69, %r70}, {%r71, %r72, %r73, %r74, %r75, %r76, %r77, %r78}, {%f90, %f91, %f92, %f93, %f94, %f95, %f96, %f97};
	add.s32 	%r79, %r117, 48;
	cvt.s64.s32 	%rd30, %r79;
	add.s64 	%rd31, %rd30, %rd3;
	shl.b64 	%rd32, %rd31, 1;
	add.s64 	%rd33, %rd2, %rd32;
	wmma.load.a.sync.aligned.row.m16n16k16.global.f16 	{%r80, %r81, %r82, %r83, %r84, %r85, %r86, %r87}, [%rd33], %r18;
	add.s64 	%rd34, %rd29, %rd5;
	wmma.load.b.sync.aligned.row.m16n16k16.global.f16 	{%r88, %r89, %r90, %r91, %r92, %r93, %r94, %r95}, [%rd34], %r17;
	wmma.mma.sync.aligned.row.row.m16n16k16.f32.f32 {%f145, %f144, %f143, %f142, %f141, %f140, %f139, %f138}, {%r80, %r81, %r82, %r83, %r84, %r85, %r86, %r87}, {%r88, %r89, %r90, %r91, %r92, %r93, %r94, %r95}, {%f98, %f99, %f100, %f101, %f102, %f103, %f104, %f105};
	add.s32 	%r117, %r117, 64;
	add.s32 	%r116, %r116, -4;
	setp.ne.s32 	%p6, %r116, 0;
	@%p6 bra 	$L__BB0_5;

$L__BB0_6:
	setp.eq.s32 	%p7, %r119, 0;
	@%p7 bra 	$L__BB0_9;

	mul.lo.s32 	%r118, %r117, %r17;
	shl.b32 	%r12, %r17, 4;
	cvt.s64.s32 	%rd35, %r117;
	add.s64 	%rd36, %rd35, %rd3;
	shl.b64 	%rd37, %rd36, 1;
	add.s64 	%rd48, %rd2, %rd37;

$L__BB0_8:
	.pragma ""nounroll"";
	wmma.load.a.sync.aligned.row.m16n16k16.global.f16 	{%r96, %r97, %r98, %r99, %r100, %r101, %r102, %r103}, [%rd48], %r18;
	cvt.s64.s32 	%rd38, %r118;
	add.s64 	%rd39, %rd38, %rd4;
	shl.b64 	%rd40, %rd39, 1;
	add.s64 	%rd41, %rd1, %rd40;
	wmma.load.b.sync.aligned.row.m16n16k16.global.f16 	{%r104, %r105, %r106, %r107, %r108, %r109, %r110, %r111}, [%rd41], %r17;
	wmma.mma.sync.aligned.row.row.m16n16k16.f32.f32 {%f145, %f144, %f143, %f142, %f141, %f140, %f139, %f138}, {%r96, %r97, %r98, %r99, %r100, %r101, %r102, %r103}, {%r104, %r105, %r106, %r107, %r108, %r109, %r110, %r111}, {%f145, %f144, %f143, %f142, %f141, %f140, %f139, %f138};
	add.s32 	%r118, %r118, %r12;
	add.s64 	%rd48, %rd48, 32;
	add.s32 	%r119, %r119, -1;
	setp.ne.s32 	%p8, %r119, 0;
	@%p8 bra 	$L__BB0_8;
	bra.uni 	$L__BB0_9;

$L__BB0_2:
	mov.f32 	%f138, 0f00000000;
	mov.f32 	%f139, %f138;
	mov.f32 	%f140, %f138;
	mov.f32 	%f141, %f138;
	mov.f32 	%f142, %f138;
	mov.f32 	%f143, %f138;
	mov.f32 	%f144, %f138;
	mov.f32 	%f145, %f138;

$L__BB0_9:
	mov.u32 	%r114, %ctaid.x;
	shl.b32 	%r113, %r114, 4;
	mul.lo.s32 	%r112, %r113, %r17;
	cvt.s64.s32 	%rd42, %r112;
	cvt.s64.s32 	%rd43, %r2;
	add.s64 	%rd44, %rd42, %rd43;
	cvta.to.global.u64 	%rd45, %rd9;
	shl.b64 	%rd46, %rd44, 2;
	add.s64 	%rd47, %rd45, %rd46;
	wmma.store.d.sync.aligned.row.m16n16k16.global.f32 	[%rd47], {%f145, %f144, %f143, %f142, %f141, %f140, %f139, %f138}, %r17;

$L__BB0_10:
	ret;

}
	// .globl	tensor_core_gemm_fp32
.visible .entry tensor_core_gemm_fp32(
	.param .u64 tensor_core_gemm_fp32_param_0,
	.param .u64 tensor_core_gemm_fp32_param_1,
	.param .u64 tensor_core_gemm_fp32_param_2,
	.param .u32 tensor_core_gemm_fp32_param_3,
	.param .u32 tensor_core_gemm_fp32_param_4,
	.param .u32 tensor_core_gemm_fp32_param_5
)
{
	.reg .pred 	%p<54>;
	.reg .b16 	%rs<97>;
	.reg .f32 	%f<89>;
	.reg .b32 	%r<179>;
	.reg .b64 	%rd<50>;
	// demoted variable
	.shared .align 2 .b8 _ZZ21tensor_core_gemm_fp32E3s_a[512];
	// demoted variable
	.shared .align 2 .b8 _ZZ21tensor_core_gemm_fp32E3s_b[512];

	ld.param.u64 	%rd13, [tensor_core_gemm_fp32_param_0];
	ld.param.u64 	%rd15, [tensor_core_gemm_fp32_param_1];
	ld.param.u32 	%r66, [tensor_core_gemm_fp32_param_3];
	ld.param.u32 	%r67, [tensor_core_gemm_fp32_param_4];
	ld.param.u32 	%r68, [tensor_core_gemm_fp32_param_5];
	cvta.to.global.u64 	%rd1, %rd15;
	mov.u32 	%r69, %ctaid.x;
	shl.b32 	%r1, %r69, 4;
	setp.ge.s32 	%p1, %r1, %r66;
	mov.u32 	%r70, %ctaid.y;
	shl.b32 	%r169, %r70, 4;
	setp.ge.s32 	%p2, %r169, %r67;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB1_53;

	setp.lt.s32 	%p4, %r68, 1;
	mov.f32 	%f81, 0f00000000;
	mov.f32 	%f82, %f81;
	mov.f32 	%f83, %f81;
	mov.f32 	%f84, %f81;
	mov.f32 	%f85, %f81;
	mov.f32 	%f86, %f81;
	mov.f32 	%f87, %f81;
	mov.f32 	%f88, %f81;
	@%p4 bra 	$L__BB1_52;

	mov.u32 	%r72, %tid.x;
	shr.s32 	%r73, %r72, 31;
	shr.u32 	%r74, %r73, 28;
	add.s32 	%r75, %r72, %r74;
	shr.s32 	%r3, %r75, 4;
	add.s32 	%r4, %r3, %r1;
	shl.b32 	%r76, %r72, 1;
	mov.u32 	%r77, _ZZ21tensor_core_gemm_fp32E3s_a;
	add.s32 	%r5, %r77, %r76;
	and.b32  	%r78, %r75, -16;
	sub.s32 	%r6, %r72, %r78;
	add.s32 	%r7, %r6, %r169;
	mov.u32 	%r79, _ZZ21tensor_core_gemm_fp32E3s_b;
	add.s32 	%r8, %r79, %r76;
	add.s32 	%r80, %r72, 32;
	shr.s32 	%r81, %r80, 31;
	shr.u32 	%r82, %r81, 28;
	add.s32 	%r83, %r80, %r82;
	shr.s32 	%r9, %r83, 4;
	and.b32  	%r84, %r83, -16;
	sub.s32 	%r10, %r80, %r84;
	add.s32 	%r11, %r9, %r1;
	add.s32 	%r12, %r10, %r169;
	add.s32 	%r85, %r72, 64;
	shr.s32 	%r86, %r85, 31;
	shr.u32 	%r87, %r86, 28;
	add.s32 	%r88, %r85, %r87;
	shr.s32 	%r13, %r88, 4;
	and.b32  	%r89, %r88, -16;
	sub.s32 	%r14, %r85, %r89;
	add.s32 	%r15, %r13, %r1;
	add.s32 	%r16, %r14, %r169;
	add.s32 	%r90, %r72, 96;
	shr.s32 	%r91, %r90, 31;
	shr.u32 	%r92, %r91, 28;
	add.s32 	%r93, %r90, %r92;
	shr.s32 	%r17, %r93, 4;
	and.b32  	%r94, %r93, -16;
	sub.s32 	%r18, %r90, %r94;
	add.s32 	%r19, %r17, %r1;
	add.s32 	%r20, %r18, %r169;
	add.s32 	%r95, %r72, 128;
	shr.s32 	%r96, %r95, 31;
	shr.u32 	%r97, %r96, 28;
	add.s32 	%r98, %r95, %r97;
	shr.s32 	%r21, %r98, 4;
	and.b32  	%r99, %r98, -16;
	sub.s32 	%r22, %r95, %r99;
	add.s32 	%r23, %r21, %r1;
	add.s32 	%r24, %r22, %r169;
	add.s32 	%r100, %r72, 160;
	shr.s32 	%r101, %r100, 31;
	shr.u32 	%r102, %r101, 28;
	add.s32 	%r103, %r100, %r102;
	shr.s32 	%r170, %r103, 4;
	and.b32  	%r104, %r103, -16;
	sub.s32 	%r26, %r100, %r104;
	add.s32 	%r27, %r170, %r1;
	add.s32 	%r28, %r26, %r169;
	add.s32 	%r105, %r72, 192;
	shr.s32 	%r106, %r105, 31;
	shr.u32 	%r107, %r106, 28;
	add.s32 	%r108, %r105, %r107;
	shr.s32 	%r173, %r108, 4;
	and.b32  	%r109, %r108, -16;
	sub.s32 	%r172, %r105, %r109;
	add.s32 	%r31, %r173, %r1;
	add.s32 	%r32, %r172, %r169;
	add.s32 	%r110, %r72, 224;
	shr.s32 	%r111, %r110, 31;
	shr.u32 	%r112, %r111, 28;
	add.s32 	%r113, %r110, %r112;
	shr.s32 	%r176, %r113, 4;
	and.b32  	%r114, %r113, -16;
	sub.s32 	%r175, %r110, %r114;
	add.s32 	%r35, %r176, %r1;
	add.s32 	%r36, %r175, %r169;
	mad.lo.s32 	%r115, %r176, %r67, %r175;
	add.s32 	%r177, %r115, %r169;
	mad.lo.s32 	%r116, %r68, %r35, %r175;
	mul.wide.s32 	%rd2, %r116, 4;
	mad.lo.s32 	%r117, %r173, %r67, %r172;
	add.s32 	%r174, %r117, %r169;
	mad.lo.s32 	%r118, %r68, %r31, %r172;
	mul.wide.s32 	%rd3, %r118, 4;
	mad.lo.s32 	%r119, %r170, %r67, %r26;
	add.s32 	%r171, %r119, %r169;
	mad.lo.s32 	%r120, %r68, %r27, %r26;
	mul.wide.s32 	%rd4, %r120, 4;
	mad.lo.s32 	%r41, %r21, %r67, %r22;
	mad.lo.s32 	%r121, %r68, %r23, %r22;
	mul.wide.s32 	%rd5, %r121, 4;
	mad.lo.s32 	%r42, %r17, %r67, %r18;
	mad.lo.s32 	%r122, %r68, %r19, %r18;
	mul.wide.s32 	%rd6, %r122, 4;
	mad.lo.s32 	%r43, %r13, %r67, %r14;
	mad.lo.s32 	%r123, %r68, %r15, %r14;
	mul.wide.s32 	%rd7, %r123, 4;
	mad.lo.s32 	%r44, %r9, %r67, %r10;
	mad.lo.s32 	%r124, %r68, %r11, %r10;
	mul.wide.s32 	%rd8, %r124, 4;
	mad.lo.s32 	%r125, %r68, %r4, %r6;
	mul.wide.s32 	%rd9, %r125, 4;
	mad.lo.s32 	%r45, %r3, %r67, %r6;
	cvta.to.global.u64 	%rd49, %rd13;
	mov.u32 	%r178, 0;
	mov.f32 	%f81, 0f00000000;

$L__BB1_3:
	add.s32 	%r126, %r6, %r178;
	setp.lt.s32 	%p5, %r126, %r68;
	setp.lt.s32 	%p6, %r4, %r66;
	and.pred  	%p7, %p6, %p5;
	@%p7 bra 	$L__BB1_5;
	bra.uni 	$L__BB1_4;

$L__BB1_5:
	add.s64 	%rd16, %rd49, %rd9;
	ld.global.nc.f32 	%f42, [%rd16];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs81, %f42;}

	// end inline asm
	bra.uni 	$L__BB1_6;

$L__BB1_4:
	mov.f32 	%f41, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs81, %f41;}

	// end inline asm

$L__BB1_6:
	st.shared.u16 	[%r5], %rs81;
	add.s32 	%r127, %r3, %r178;
	setp.lt.s32 	%p8, %r127, %r68;
	setp.lt.s32 	%p9, %r7, %r67;
	and.pred  	%p10, %p8, %p9;
	@%p10 bra 	$L__BB1_8;
	bra.uni 	$L__BB1_7;

$L__BB1_8:
	add.s32 	%r128, %r45, %r169;
	mul.wide.s32 	%rd17, %r128, 4;
	add.s64 	%rd18, %rd1, %rd17;
	ld.global.nc.f32 	%f44, [%rd18];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs82, %f44;}

	// end inline asm
	bra.uni 	$L__BB1_9;

$L__BB1_7:
	mov.f32 	%f43, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs82, %f43;}

	// end inline asm

$L__BB1_9:
	st.shared.u16 	[%r8], %rs82;
	add.s32 	%r129, %r10, %r178;
	setp.lt.s32 	%p11, %r129, %r68;
	setp.lt.s32 	%p12, %r11, %r66;
	and.pred  	%p13, %p12, %p11;
	@%p13 bra 	$L__BB1_11;
	bra.uni 	$L__BB1_10;

$L__BB1_11:
	add.s64 	%rd19, %rd49, %rd8;
	ld.global.nc.f32 	%f46, [%rd19];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs83, %f46;}

	// end inline asm
	bra.uni 	$L__BB1_12;

$L__BB1_10:
	mov.f32 	%f45, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs83, %f45;}

	// end inline asm

$L__BB1_12:
	st.shared.u16 	[%r5+64], %rs83;
	add.s32 	%r130, %r9, %r178;
	setp.lt.s32 	%p14, %r130, %r68;
	setp.lt.s32 	%p15, %r12, %r67;
	and.pred  	%p16, %p14, %p15;
	@%p16 bra 	$L__BB1_14;
	bra.uni 	$L__BB1_13;

$L__BB1_14:
	add.s32 	%r131, %r44, %r169;
	mul.wide.s32 	%rd20, %r131, 4;
	add.s64 	%rd21, %rd1, %rd20;
	ld.global.nc.f32 	%f48, [%rd21];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs84, %f48;}

	// end inline asm
	bra.uni 	$L__BB1_15;

$L__BB1_13:
	mov.f32 	%f47, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs84, %f47;}

	// end inline asm

$L__BB1_15:
	st.shared.u16 	[%r8+64], %rs84;
	add.s32 	%r132, %r14, %r178;
	setp.lt.s32 	%p17, %r132, %r68;
	setp.lt.s32 	%p18, %r15, %r66;
	and.pred  	%p19, %p18, %p17;
	@%p19 bra 	$L__BB1_17;
	bra.uni 	$L__BB1_16;

$L__BB1_17:
	add.s64 	%rd22, %rd49, %rd7;
	ld.global.nc.f32 	%f50, [%rd22];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs85, %f50;}

	// end inline asm
	bra.uni 	$L__BB1_18;

$L__BB1_16:
	mov.f32 	%f49, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs85, %f49;}

	// end inline asm

$L__BB1_18:
	st.shared.u16 	[%r5+128], %rs85;
	add.s32 	%r133, %r13, %r178;
	setp.lt.s32 	%p20, %r133, %r68;
	setp.lt.s32 	%p21, %r16, %r67;
	and.pred  	%p22, %p20, %p21;
	@%p22 bra 	$L__BB1_20;
	bra.uni 	$L__BB1_19;

$L__BB1_20:
	add.s32 	%r134, %r43, %r169;
	mul.wide.s32 	%rd23, %r134, 4;
	add.s64 	%rd24, %rd1, %rd23;
	ld.global.nc.f32 	%f52, [%rd24];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs86, %f52;}

	// end inline asm
	bra.uni 	$L__BB1_21;

$L__BB1_19:
	mov.f32 	%f51, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs86, %f51;}

	// end inline asm

$L__BB1_21:
	st.shared.u16 	[%r8+128], %rs86;
	add.s32 	%r135, %r18, %r178;
	setp.lt.s32 	%p23, %r135, %r68;
	setp.lt.s32 	%p24, %r19, %r66;
	and.pred  	%p25, %p24, %p23;
	@%p25 bra 	$L__BB1_23;
	bra.uni 	$L__BB1_22;

$L__BB1_23:
	add.s64 	%rd25, %rd49, %rd6;
	ld.global.nc.f32 	%f54, [%rd25];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs87, %f54;}

	// end inline asm
	bra.uni 	$L__BB1_24;

$L__BB1_22:
	mov.f32 	%f53, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs87, %f53;}

	// end inline asm

$L__BB1_24:
	st.shared.u16 	[%r5+192], %rs87;
	add.s32 	%r136, %r17, %r178;
	setp.lt.s32 	%p26, %r136, %r68;
	setp.lt.s32 	%p27, %r20, %r67;
	and.pred  	%p28, %p26, %p27;
	@%p28 bra 	$L__BB1_26;
	bra.uni 	$L__BB1_25;

$L__BB1_26:
	add.s32 	%r137, %r42, %r169;
	mul.wide.s32 	%rd26, %r137, 4;
	add.s64 	%rd27, %rd1, %rd26;
	ld.global.nc.f32 	%f56, [%rd27];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs88, %f56;}

	// end inline asm
	bra.uni 	$L__BB1_27;

$L__BB1_25:
	mov.f32 	%f55, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs88, %f55;}

	// end inline asm

$L__BB1_27:
	st.shared.u16 	[%r8+192], %rs88;
	add.s32 	%r138, %r22, %r178;
	setp.lt.s32 	%p29, %r138, %r68;
	setp.lt.s32 	%p30, %r23, %r66;
	and.pred  	%p31, %p30, %p29;
	@%p31 bra 	$L__BB1_29;
	bra.uni 	$L__BB1_28;

$L__BB1_29:
	add.s64 	%rd28, %rd49, %rd5;
	ld.global.nc.f32 	%f58, [%rd28];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs89, %f58;}

	// end inline asm
	bra.uni 	$L__BB1_30;

$L__BB1_28:
	mov.f32 	%f57, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs89, %f57;}

	// end inline asm

$L__BB1_30:
	st.shared.u16 	[%r5+256], %rs89;
	add.s32 	%r139, %r21, %r178;
	setp.lt.s32 	%p32, %r139, %r68;
	setp.lt.s32 	%p33, %r24, %r67;
	and.pred  	%p34, %p32, %p33;
	@%p34 bra 	$L__BB1_32;
	bra.uni 	$L__BB1_31;

$L__BB1_32:
	add.s32 	%r140, %r41, %r169;
	mul.wide.s32 	%rd29, %r140, 4;
	add.s64 	%rd30, %rd1, %rd29;
	ld.global.nc.f32 	%f60, [%rd30];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs90, %f60;}

	// end inline asm
	bra.uni 	$L__BB1_33;

$L__BB1_31:
	mov.f32 	%f59, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs90, %f59;}

	// end inline asm

$L__BB1_33:
	st.shared.u16 	[%r8+256], %rs90;
	add.s32 	%r141, %r26, %r178;
	setp.lt.s32 	%p35, %r141, %r68;
	setp.lt.s32 	%p36, %r27, %r66;
	and.pred  	%p37, %p36, %p35;
	@%p37 bra 	$L__BB1_35;
	bra.uni 	$L__BB1_34;

$L__BB1_35:
	add.s64 	%rd31, %rd49, %rd4;
	ld.global.nc.f32 	%f62, [%rd31];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs91, %f62;}

	// end inline asm
	bra.uni 	$L__BB1_36;

$L__BB1_34:
	mov.f32 	%f61, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs91, %f61;}

	// end inline asm

$L__BB1_36:
	st.shared.u16 	[%r5+320], %rs91;
	setp.lt.s32 	%p38, %r170, %r68;
	setp.lt.s32 	%p39, %r28, %r67;
	and.pred  	%p40, %p38, %p39;
	@%p40 bra 	$L__BB1_38;
	bra.uni 	$L__BB1_37;

$L__BB1_38:
	mul.wide.s32 	%rd32, %r171, 4;
	add.s64 	%rd33, %rd1, %rd32;
	ld.global.nc.f32 	%f64, [%rd33];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs92, %f64;}

	// end inline asm
	bra.uni 	$L__BB1_39;

$L__BB1_37:
	mov.f32 	%f63, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs92, %f63;}

	// end inline asm

$L__BB1_39:
	st.shared.u16 	[%r8+320], %rs92;
	setp.lt.s32 	%p41, %r172, %r68;
	setp.lt.s32 	%p42, %r31, %r66;
	and.pred  	%p43, %p42, %p41;
	@%p43 bra 	$L__BB1_41;
	bra.uni 	$L__BB1_40;

$L__BB1_41:
	add.s64 	%rd34, %rd49, %rd3;
	ld.global.nc.f32 	%f66, [%rd34];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs93, %f66;}

	// end inline asm
	bra.uni 	$L__BB1_42;

$L__BB1_40:
	mov.f32 	%f65, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs93, %f65;}

	// end inline asm

$L__BB1_42:
	st.shared.u16 	[%r5+384], %rs93;
	setp.lt.s32 	%p44, %r173, %r68;
	setp.lt.s32 	%p45, %r32, %r67;
	and.pred  	%p46, %p44, %p45;
	@%p46 bra 	$L__BB1_44;
	bra.uni 	$L__BB1_43;

$L__BB1_44:
	mul.wide.s32 	%rd35, %r174, 4;
	add.s64 	%rd36, %rd1, %rd35;
	ld.global.nc.f32 	%f68, [%rd36];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs94, %f68;}

	// end inline asm
	bra.uni 	$L__BB1_45;

$L__BB1_43:
	mov.f32 	%f67, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs94, %f67;}

	// end inline asm

$L__BB1_45:
	st.shared.u16 	[%r8+384], %rs94;
	setp.lt.s32 	%p47, %r175, %r68;
	setp.lt.s32 	%p48, %r35, %r66;
	and.pred  	%p49, %p48, %p47;
	@%p49 bra 	$L__BB1_47;
	bra.uni 	$L__BB1_46;

$L__BB1_47:
	add.s64 	%rd37, %rd49, %rd2;
	ld.global.nc.f32 	%f70, [%rd37];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs95, %f70;}

	// end inline asm
	bra.uni 	$L__BB1_48;

$L__BB1_46:
	mov.f32 	%f69, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs95, %f69;}

	// end inline asm

$L__BB1_48:
	st.shared.u16 	[%r5+448], %rs95;
	setp.lt.s32 	%p50, %r176, %r68;
	setp.lt.s32 	%p51, %r36, %r67;
	and.pred  	%p52, %p50, %p51;
	@%p52 bra 	$L__BB1_50;
	bra.uni 	$L__BB1_49;

$L__BB1_50:
	mul.wide.s32 	%rd38, %r177, 4;
	add.s64 	%rd39, %rd1, %rd38;
	ld.global.nc.f32 	%f72, [%rd39];
	// begin inline asm
	{  cvt.rn.f16.f32 %rs96, %f72;}

	// end inline asm
	bra.uni 	$L__BB1_51;

$L__BB1_49:
	mov.f32 	%f71, 0f00000000;
	// begin inline asm
	{  cvt.rn.f16.f32 %rs96, %f71;}

	// end inline asm

$L__BB1_51:
	shl.b32 	%r164, %r67, 4;
	mov.u32 	%r163, _ZZ21tensor_core_gemm_fp32E3s_b;
	mov.u32 	%r162, _ZZ21tensor_core_gemm_fp32E3s_a;
	st.shared.u16 	[%r8+448], %rs96;
	bar.warp.sync 	-1;
	mov.u32 	%r142, 16;
	wmma.load.a.sync.aligned.row.m16n16k16.shared.f16 	{%r144, %r145, %r146, %r147, %r148, %r149, %r150, %r151}, [%r162], %r142;
	wmma.load.b.sync.aligned.row.m16n16k16.shared.f16 	{%r153, %r154, %r155, %r156, %r157, %r158, %r159, %r160}, [%r163], %r142;
	wmma.mma.sync.aligned.row.row.m16n16k16.f32.f32 {%f88, %f87, %f86, %f85, %f84, %f83, %f82, %f81}, {%r144, %r145, %r146, %r147, %r148, %r149, %r150, %r151}, {%r153, %r154, %r155, %r156, %r157, %r158, %r159, %r160}, {%f88, %f87, %f86, %f85, %f84, %f83, %f82, %f81};
	bar.warp.sync 	-1;
	add.s32 	%r177, %r177, %r164;
	add.s32 	%r176, %r176, 16;
	add.s64 	%rd49, %rd49, 64;
	add.s32 	%r175, %r175, 16;
	add.s32 	%r174, %r174, %r164;
	add.s32 	%r173, %r173, 16;
	add.s32 	%r172, %r172, 16;
	add.s32 	%r171, %r171, %r164;
	add.s32 	%r170, %r170, 16;
	add.s32 	%r169, %r169, %r164;
	add.s32 	%r178, %r178, 16;
	setp.lt.s32 	%p53, %r178, %r68;
	@%p53 bra 	$L__BB1_3;

$L__BB1_52:
	ld.param.u64 	%rd48, [tensor_core_gemm_fp32_param_2];
	mov.u32 	%r168, %ctaid.y;
	shl.b32 	%r167, %r168, 4;
	mov.u32 	%r166, %ctaid.x;
	shl.b32 	%r165, %r166, 4;
	mul.lo.s32 	%r161, %r165, %r67;
	cvt.s64.s32 	%rd42, %r161;
	cvt.s64.s32 	%rd43, %r167;
	add.s64 	%rd44, %rd42, %rd43;
	cvta.to.global.u64 	%rd45, %rd48;
	shl.b64 	%rd46, %rd44, 2;
	add.s64 	%rd47, %rd45, %rd46;
	wmma.store.d.sync.aligned.row.m16n16k16.global.f32 	[%rd47], {%f88, %f87, %f86, %f85, %f84, %f83, %f82, %f81}, %r67;

$L__BB1_53:
	ret;

}

";
}
